version: '3'
volumes:
  dados: 
services: 
  db:
    image: postgres:9.6
    volumes: 
    # Volume dos dados
    - dados:/var/lib/postgresql/data
    # scripts
    - ./scripts:/scripts
    - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: ./app
    ports:
      - "3000:3000"   
