
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('vote_meme_page').del()
    .then(function () {
      // Inserts seed entries
      return knex('vote_meme_page').insert([
        //1
        {id_user: 1, id_post: 3, up: 1, down: null},
        {id_user: 1, id_post: 4, up: 1, down: null},
        {id_user: 1, id_post: 5, up: 1, down: null},
        {id_user: 1, id_post: 6, up: 1, down: null},
        {id_user: 1, id_post: 7, down: 1, up: null},
        {id_user: 1, id_post: 8, up: 1, down: null},
        {id_user: 1, id_post: 9, up: 1, down: null},
        {id_user: 1, id_post: 10, down: 1, up: null},
        {id_user: 1, id_post: 11, up: 1, down: null},
        {id_user: 1, id_post: 12, up: 1, down: null},
        {id_user: 1, id_post: 13, down: 1, up: null},
        {id_user: 1, id_post: 14, up: 1, down: null},
        //2
        {id_user: 2, id_post: 1, up: 1, down: null},
        {id_user: 2, id_post: 2, up: 1, down: null},
        {id_user: 2, id_post: 6, up: 1, down: null},
        {id_user: 2, id_post: 7, down: 1, up: null},
        {id_user: 2, id_post: 8, up: 1, down: null},
        {id_user: 2, id_post: 9, up: 1, down: null},
        {id_user: 2, id_post: 10, down: 1, up: null},
        {id_user: 2, id_post: 11, up: 1, down: null},
        {id_user: 2, id_post: 12, up: 1, down: null},
        {id_user: 2, id_post: 13, down: 1, up: null},
        {id_user: 2, id_post: 14, up: 1, down: null},
        //3
        {id_user: 3, id_post: 1, up: 1, down: null},
        {id_user: 3, id_post: 2, up: 1, down: null},
        {id_user: 3, id_post: 4, up: 1, down: null},
        {id_user: 3, id_post: 5, up: 1, down: null},
        {id_user: 3, id_post: 3, up: 1, down: null},
        {id_user: 3, id_post: 7, down: 1, up: null},
        {id_user: 3, id_post: 8, up: 1, down: null},
        {id_user: 3, id_post: 9, up: 1, down: null},
        {id_user: 3, id_post: 10, down: 1, up: null},
        {id_user: 3, id_post: 11, up: 1, down: null},
        {id_user: 3, id_post: 12, up: 1, down: null},
        {id_user: 3, id_post: 13, down: 1, up: null},
        {id_user: 3, id_post: 14, up: 1, down: null},
        //4
        {id_user: 4, id_post: 1, up: 1, down: null},
        {id_user: 4, id_post: 2, up: 1, down: null},
        {id_user: 4, id_post: 4, up: 1, down: null},
        {id_user: 4, id_post: 5, up: 1, down: null},
        {id_user: 4, id_post: 3, up: 1, down: null},
        {id_user: 4, id_post: 6, down: 1, up: null},
        {id_user: 4, id_post: 9, up: 1, down: null},
        {id_user: 4, id_post: 10, down: 1, up: null},
        {id_user: 4, id_post: 11, up: 1, down: null},
        {id_user: 4, id_post: 12, up: 1, down: null},
        {id_user: 4, id_post: 13, down: 1, up: null},
        {id_user: 4, id_post: 14, up: 1, down: null},
        //5
        {id_user: 5, id_post: 1, up: 1, down: null},
        {id_user: 5, id_post: 2, up: 1, down: null},
        {id_user: 5, id_post: 4, up: 1, down: null},
        {id_user: 5, id_post: 5, up: 1, down: null},
        {id_user: 5, id_post: 3, up: 1, down: null},
        {id_user: 5, id_post: 7, down: 1, up: null},
        {id_user: 5, id_post: 6, up: 1, down: null},
        {id_user: 5, id_post: 10, down: 1, up: null},
        {id_user: 5, id_post: 11, up: 1, down: null},
        {id_user: 5, id_post: 12, up: 1, down: null},
        {id_user: 5, id_post: 13, down: 1, up: null},
        {id_user: 5, id_post: 14, up: 1, down: null},
        //6
        {id_user: 6, id_post: 1, up: 1, down: null},
        {id_user: 6, id_post: 2, up: 1, down: null},
        {id_user: 6, id_post: 4, up: 1, down: null},
        {id_user: 6, id_post: 5, up: 1, down: null},
        {id_user: 6, id_post: 3, up: 1, down: null},
        {id_user: 6, id_post: 7, down: 1, up: null},
        {id_user: 6, id_post: 8, up: 1, down: null},
        {id_user: 6, id_post: 9, up: 1, down: null},
        {id_user: 6, id_post: 6, down: 1, up: null},
        {id_user: 6, id_post: 11, up: 1, down: null},
        {id_user: 6, id_post: 12, up: 1, down: null},
        {id_user: 6, id_post: 13, down: 1, up: null},
        {id_user: 6, id_post: 14, up: 1, down: null},
        //7
        {id_user: 7, id_post: 1, up: 1, down: null},
        {id_user: 7, id_post: 2, up: 1, down: null},
        {id_user: 7, id_post: 4, up: 1, down: null},
        {id_user: 7, id_post: 5, up: 1, down: null},
        {id_user: 7, id_post: 3, up: 1, down: null},
        {id_user: 7, id_post: 7, down: 1, up: null},
        {id_user: 7, id_post: 8, up: 1, down: null},
        {id_user: 7, id_post: 9, up: 1, down: null},
        {id_user: 7, id_post: 10, down: 1, up: null},
        {id_user: 7, id_post: 6, up: 1, down: null},
        {id_user: 7, id_post: 12, up: 1, down: null},
        {id_user: 7, id_post: 13, down: 1, up: null},
        {id_user: 7, id_post: 14, up: 1, down: null},
        //8
        {id_user: 8, id_post: 1, up: 1, down: null},
        {id_user: 8, id_post: 2, up: 1, down: null},
        {id_user: 8, id_post: 4, up: 1, down: null},
        {id_user: 8, id_post: 5, up: 1, down: null},
        {id_user: 8, id_post: 3, up: 1, down: null},
        {id_user: 8, id_post: 7, down: 1, up: null},
        {id_user: 8, id_post: 8, up: 1, down: null},
        {id_user: 8, id_post: 9, up: 1, down: null},
        {id_user: 8, id_post: 10, down: 1, up: null},
        {id_user: 8, id_post: 11, up: 1, down: null},
        {id_user: 8, id_post: 6, up: 1, down: null},
        {id_user: 8, id_post: 13, down: 1, up: null},
        {id_user: 8, id_post: 14, up: 1, down: null},
        //9
        {id_user: 9, id_post: 1, up: 1, down: null},
        {id_user: 9, id_post: 2, up: 1, down: null},
        {id_user: 9, id_post: 4, up: 1, down: null},
        {id_user: 9, id_post: 5, up: 1, down: null},
        {id_user: 9, id_post: 3, up: 1, down: null},
        {id_user: 9, id_post: 7, down: 1, up: null},
        {id_user: 9, id_post: 8, up: 1, down: null},
        {id_user: 9, id_post: 9, up: 1, down: null},
        {id_user: 9, id_post: 10, down: 1, up: null},
        {id_user: 9, id_post: 11, up: 1, down: null},
        {id_user: 9, id_post: 12, up: 1, down: null},
        {id_user: 9, id_post: 6, down: 1, up: null},
        {id_user: 9, id_post: 14, up: 1, down: null},
        //10
        {id_user: 10, id_post: 1, up: 1, down: null},
        {id_user: 10, id_post: 2, up: 1, down: null},
        {id_user: 10, id_post: 4, up: 1, down: null},
        {id_user: 10, id_post: 5, up: 1, down: null},
        {id_user: 10, id_post: 3, up: 1, down: null},
        {id_user: 10, id_post: 7, down: 1, up: null},
        {id_user: 10, id_post: 8, up: 1, down: null},
        {id_user: 10, id_post: 9, up: 1, down: null},
        {id_user: 10, id_post: 10, down: 1, up: null},
        {id_user: 10, id_post: 11, up: 1, down: null},
        {id_user: 10, id_post: 12, up: 1, down: null},
        {id_user: 10, id_post: 13, down: 1, up: null},
        {id_user: 10, id_post: 6, up: 1, down: null}
      ]);
    });
};
